### ISSUE TITLE
US01 - Realizar o cadastramento do usuário

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#16]
## Descrição da História

Eu, como usuário, gostaria de realizar meu cadastro de conta no sistema

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve incluir campos obrigatórios como nome, e-mail, senha, gênero e idade 
- [ ] O Sistema deve validar os dados inseridos, garantindo que o e-mail não esteja já em uso ou formatos inválidos
- [ ] O Sistema deve incluir todas as informações inseridas do usuário

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] O email deve ser único
- [ ] Deve haver uma mensagem de erro caso algum dado esteja inválido
- [ ] Os dados devem ser persistidos
