### ISSUE TITLE
US02 - Obter os dados físicos da pessoa

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#17]
## Descrição da História

Eu, como usuário, gostaria de fazer e verificar meu peso e altura para visualizar o meu IMC do corpo.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve coletar os dados de seu peso
- [ ] O sistema deve coletar os dados de sua altura
- [ ] O sistema deve coletar sua idade
- [ ] O Sistema deve calcular o IMC do usuário

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Ver a seção de coleta de seu peso e altura
- [ ] Inserir as seu peso e altura
- [ ] Gravar as informações
- [ ] Visualizar seu IMC
