### ISSUE TITLE
US04 - Obter moedas por exercícios realizados

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#18]
## Descrição da História

Eu, como usuário, gostaria de ganhar moedas equivalente ao nível de esforço que fiz de exercício físico no dia, definindo um limite máximo de moedas por dia.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deverá obter o nível calorias gastas no dia
- [ ] O sistema deverá acrescentar moedas ao usuário equivalente a uma porcentagem de acordo com nível de calorias gastas no dia
- [ ] O sistema deverá possuir um limite máximo a se obter as moedas de acordo com as caloria ganhas por semana

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Ver a quantidade de moedas atuais
- [ ] Adquirir moedas ao finalizar um exercício
