### ISSUE TITLE
US05 - Inscrição dos campeonatos

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#19]
## Descrição da História

Eu, como usuário, gostaria de gastar minhas moedas para me inscrever em um dos campeonatos disponíveis

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve conter uma lista de campeonatos:
- - [ ] Para cada campeonato, deve possuir vagas limitadas de inscrições
- - [ ] Para cada campeonato, deve informar se ela está na situação ou Aberta, ou Em andamento, ou Finalizada.
- - [ ] Para cada campeonato Aberta, deve informar o preço da inscrição
- - [ ] Para cada campeonato para todas as situações, deve informar o prêmio a ser bonificado ao término do mesmo
- - [ ] Para cada campeonato Em andamento, o mesmo deverá ter o tempo para entrar na situação de Finalizada
- - [ ] Para cada campeonato, deve-se informar se a categoria do mesmo é Solo ou Em equipe

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar a lista de campeonatos
- [ ] Se inscrever em um campeonato
