### ISSUE TITLE
US03 - Visualizar o histórico de exercícios praticados

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#20]
## Descrição da História

Eu, como usuário, gostaria de visualizar todos os meus registros de atividades físicas.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve possuir uma lista do histórico com os dias que o usuário fez a atividade física
- [ ] O sistema deve possuir os dados de calorias gastas aos dias em que o usuário fez atividade física
- [ ] O sistema deve possuir o quanto de moedas adquiri no dia

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar a lista do histórico das atividades físicas feitos pelo usuário
- [ ] A lista deve conter uma paginação de atividades mensal 
- [ ] Visualizar o dia, a caloria gasta e as moedas para cada registro no histórico
