### ISSUE TITLE
US06 - Competir com os usuários do campeonato

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#21]
## Descrição da História

Eu, como usuário, gostaria competir com os usuários inscritos no campeonato o qual eu me inscrevi, até o tempo estipulado acabar e receber o meu prêmio.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O campeonato do sistema deve listar todos os jogadores ou equipes o qual se inscreveram, bem como quantidade de inscritos e a capacidade máxima que poderá entrar no mesmo
- - [ ] A lista dos jogadores ou equipe devem estar ordenado de forma crescente pela quantidade de pontos obtidos por cada participante do campeonato inscrito.
- [ ] O campeonato do sistema deve possuir a data e o horário que irá iniciar o evento e a situação do mesmo (Aberto, Em andamento, Finalizada)
- [ ] O campeonato do sistema deve possuir o tempo de término ao entrar na situação de Em andamento definido pelo responsável do campeonato
- [ ] O sistema deve notificar todos os usuários participantes do campeonato selecionado quando o mesmo entrar na situação Em andamento.

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar a lista de jogadores no campeonato
- [ ] Visualizar a quantidade de participantes, assim como a sua capacidade máxima
- [ ] Receber a notificação do início do campeonato
- [ ] Visualizar o prêmio do campeonato
