### ISSUE TITLE
US07 - Criação de grupo

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#22]
## Descrição da História

Eu, como usuário, gostaria de criar um grupo e convidar meus amigos para incentivar uns aos outros a praticar exercícios físicos.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve possuir o cadastramento do grupo para o usuário realizar
- [ ] O sistema deve permitir inserir o nome do grupo
- [ ] O sistema deve permitir a seleção de uma das fotos pré-definidas do sistema
- [ ] O sistema deve gerar o código único do grupo para que somente o usuário administrador do grupo possa copiar e compartilhar o código para outros usuários o qual queria convidar para o grupo
- [ ] O sistema deverá ter a lista de pedido para entrar ou não no grupo somente para os administradores do grupo
- [ ] O grupo no sistema deverá ter chat para os amigos conversarem entre si

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar os integrantes do grupo
- [ ] Visualizar o código do grupo, caso o mesmo seja administrador do grupo
- [ ] Visualizar a lista de pedidos para entrar no grupo
- [ ] Mandar mensagem no chat do grupo
- [ ] Visualizar as suas próprias mensagens e a dos outros membros
