### ISSUE TITLE
US08 - Recuperar a conta

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#23]
## Descrição da História

Eu, como usuário, gostaria de realizar minha recuperação de conta a partir do e-mail, redefinindo uma nova senha para a minha conta, uma vez que esqueci.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve possuir um botão de cunho opcional para o usuário clicar e ser redirecionado ao passo a passo de recuperar a conta
- [ ] O sistema deve conter um input para o usuário inserir o e-mail da conta vinculada, o qual foi perdida.
- [ ] O sistema deve analisar em primeira análise se existe uma conta criada a partir do e-mail inserido na plataforma 
- [ ] O sistema deve enviar o pedido de redefinição de senha para o e-mail do usuário, caso a conta exista a partir do e-mail inserido
- [ ] O sistema deve atualizar a senha do usuário vinculado a conta que ele foi perdida

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar o botão de recuperar a conta
- [ ] Inserir o e-mail da conta vinculada
- [ ] Receber o e-mail para a redefinição de senha
- [ ] Acessar a conta anteriormente perdida a partir da nova senha redefinida
