### ISSUE TITLE
US09 - Acessar as estatísticas de outros usuários

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#24]
## Descrição da História

Eu, como usuário, gostaria de visualizar as estatísticas de outros usuários em gráficos, como seus dias de atividades físicas realizadas e moedas ganhas, suas moedas totais no momento.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve possuir um gráfico comparativo dos dias que o usuário logado e o usuário do perfil realizaram, além de quantas moedas adquiriram no dia
- [ ] O sistema deve possuir o nome e a data o qual o usuário do perfil entrou na plataforma
- [ ] O sistema deve possuir o grupo o qual o usuário do perfil está participando, caso tenha
- [ ] O sistema deve conter as moedas que o usuário do perfil possui
- [ ] O sistema deve conter o histórico dos campeonatos o qual o usuário do perfil participou e qual posição de cada campeonato o mesmo ficou
- [ ] O sistema deve ter a possibilidade de adicionar como amigo o usuário do perfil
- [ ] O sistema deve ter a possibilidade de remover como amigo o usuário de perfil
- [ ] O sistema deve ter a possibilidade de convidar o usuário do perfil à entrar no grupo criado pelo usuário logado, caso ambos sejam amigos.

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar um perfil de usuário
- [ ] Visualizar a comparação de seu desenvolvimento com o usuário do perfil
- [ ] Adicionar como amigo o usuário
- [ ] Remover o amigo
- [ ] Convidar o usuário do perfil para o grupo
