### ISSUE TITLE
US10 - Criar o personagem

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#25]
## Descrição da História

Eu, como usuário, gostaria de criar meu personagem da forma que eu desejo.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve ter um personagem default para ser utilizado como personagem do usuário
- [ ] O sistema deve possibilitar a escolha de cabelos independente do sexo selecionado
- [ ] O sistema deve possibilitar a escolha da cor de pele do personagem
- [ ] O sistema deve possibilitar a escolha de facetas no personagem
- [ ] O sistema deve possibilitar a escolha de vestimentas do personagem
- - [ ] O sistema deve possibilitar a alteração de cor da vestimenta escolhida
- [ ] O sistema deve possibilitar a confirmação do personagem realizado pelo usuário 

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar o personagem do usuário
- [ ] Alterar o cabelo do personagem
- [ ] Alterar a cor de pele do personagem
- [ ] Alterar as facetar do personagem
- [ ] Alterar as vestimentas do personagem
- [ ] Alterar a cor das vestimentas do personagem
- [ ] Confirmar as mudanças feitas do personagem pelo usuário
