### ISSUE TITLE
US11 - Gastar em loja de customização

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#26]
## Descrição da História

Eu, como usuário, gostaria de gastar minhas moedas para a loja da plataforma, onde deverá possuir customizações para o meu personagem.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve possuir uma seção na loja com customizações para o personagem do usuário
- - [ ] A loja do sistema deve possuir diversos cabelos para o personagem do usuário, cada qual com seu preço
- - [ ] A loja do sistema deve possuir diversos acessórios para o personagem do usuário, cada qual com seu preço
- - [ ] A loja do sistema deve possuir diversas facetas para o personagem do usuário, cada qual com seu preço
- - [ ] A loja do sistema deve possuir diversas vestimentas para o personagem do usuário, cada qual com seu preço
- [ ] As moedas da loja devem ser diferente da que é usado para a inscrição nos campeonatos.
- [ ] O sistema deve efetivar as comprar dos itens que o usuário selecionou

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar a loja no tópico de cabelos
- [ ] Visualizar a loja no tópico de acessórios
- [ ] Visualizar a loja no tópico de facetas
- [ ] Visualizar a loja no tópico de vestimentas
