### ISSUE TITLE
US12 - Receber desafios

### ISSUE THREAD

**Issue by DaviRogs1** [mdsreq-fga-unb/2024.1-RPGym#27]
## Descrição da História

Eu, como usuário, gostaria de receber desafios diários e semanais para serem realizados durante o dia/semana, e para cada desafio cumprida, serei recompensada com as moedas de ingressos e moedas para usar na loja.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve atualizar as missões a cada dia início de dia de forma aleatória para cada usuário
- [ ] O sistema deve atualizar as missões a cada início de semana de forma aleatória par cada usuário
- [ ] O sistema deve bonificar o usuário que cumprir com algum dos desafios disponibilizado ao usuário
- - [ ] Para cada desafio, deve ser entregue uma quantidade X de moedas para a inscrição e Y para as moedas da loja de customização
- [ ] O sistema deve ficar inacessível de cumprir novamente caso o usuário já tenha realizado o desafio no dia ou semana
- [ ] Para cada desafio a completar, deverá ter o progresso do qual próximo de finalizar estará

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar a descrição dos desafios
- [ ] Visualizar o progresso dos desafios para completar
- [ ] Visualizar a bonificação de cada desafio ainda a completar
