### ISSUE TITLE
US13 - Realizar o login do usuário

### ISSUE THREAD

**Issue by matix0** [mdsreq-fga-unb/2024.1-RPGym#28]
## Descrição da História

Eu, como usuário, gostaria de realizar meu login de conta no sistema

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O usuário deve ser capaz de acessar o sistema utilizando login e senha anteriormente cadastrados

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] O login e senha devem estar corretos
- [ ] Caso um dos dois estejam incorretos deve ser apresentada uma mensagem de erro
