### ISSUE TITLE
US14 - Edição de Dados

### ISSUE THREAD

**Issue by matix0** [mdsreq-fga-unb/2024.1-RPGym#29]
## Descrição da História

Eu, como usuário, gostaria de editar minhas informações na plataforma.

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O Sistema deve ter a possibilidade de editar os campos como o nome, e-mail, senha, gênero e idade
- [ ] O sistema deve validar as novas informações antes de salvá-las
- [ ] O sistema deve possuir a opção de excluir a conta

## Critérios de Avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Caso algum dado inserido na edição seja inválido, deve haver uma mensagem de erro
- [ ] Persistir as mudanças de suas informações
- [ ] Realizar a exclusão de sua conta
- [ ] Deve haver uma confirmação para excluir a conta
