### ISSUE TITLE
US15 - Cancelamento da inscrição dos campeonatos

### ISSUE THREAD

**Issue by DaviRogs** [mdsreq-fga-unb/2024.1-RPGym#30]
## Descrição de história

Eu, como usuário, gostaria de cancelar a inscrição em um dos campeonatos o qual realizei a inscrição

## Tasks

As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve possuir a opção para o cancelamento do campeonato (#19)  se somente o mesmo ainda estiver Em Aberto
- [ ] Caso o usuário tenha cancelado, o mesmo deverá receber um estorno de 60% das moedas (#18) gastas da inscrição do torneio

## Critérios de Avaliação

- [ ] Cancelar um torneio o qual está inscrito, caso o mesmo
- [ ] Visualizar o recebimento do estorno de 60% do valor da inscrição do torneiro anteriormente inscrito
