### ISSUE TITLE
US16 - Edição das informações do grupo

### ISSUE THREAD

**Issue by DaviRogs** [mdsreq-fga-unb/2024.1-RPGym#31]
## Descrição da História

Eu, como usuário, gostaria de editar as informações do meu grupo o qual criei

## Tasks

- [ ] O sistema deverá possuir uma opção para editar as informações do grupo (#22) somente se o usuário possuir a administração do grupo
- [ ] O sistema deve bloquear a edição caso o usuário não possua a administração
- [ ] O sistema deverá editar o nome e uma foto pré-definidas do sistema
- [ ] O sistema deverá confirmar e registrar as novas alterações feitas
- [ ] O sistema deverá ter a opção de cancelar o pedido de alteração do grupo

## Critérios de avaliação

- [ ] Visualizar a opção de editar grupo, caso o usuário seja administrador
- [ ] liberar a edição das informações do grupo, caso tenha pedido a edição
- [ ] Editar o nome do grupo
- [ ] Mudar a foto do grupo
- [ ] Cancelar a edição do grupo
- [ ] Confirmar a edição do grupo
