### ISSUE TITLE
US17 - Exclusão do grupo

### ISSUE THREAD

**Issue by DaviRogs** [mdsreq-fga-unb/2024.1-RPGym#32]
## Descrição da História

Eu, como usuário, gostaria de excluir um grupo que criei anteriormente

## Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deverá possuir uma opção para excluir as informações do grupo (#22), somente se o usuário for o criador do grupo
- [ ] O sistema deverá expulsar todos os usuários que estiverem no grupo, caso o grupo tenha sido excluído
- [ ] O sistema deverá confirmar o pedido de exclusão do grupo, antes de excluir de fato
- [ ] O sistema deverá notificar todos os usuários que estavam no grupo de que o grupo foi excluído
- [ ] O sistema deve apagar o código criado no banco de dados para o grupo para que seja utilizado em um próximo grupo a ser criado de um usuário qualquer

## Critérios de Avaliação

- [ ] Visualizar a opção de exclusão do grupo, caso o usuário seja o criador do grupo
- [ ] Confirmar o pedido de exclusão, caso tenha pedido a exclusão
- [ ] Notificar os usuários do grupo
- [ ] Expulsar os usuários do grupo
- [ ] Excluir o grupo
