### ISSUE TITLE
US18 - Expulsar usuário do grupo

### ISSUE THREAD

**Issue by DaviRogs** [mdsreq-fga-unb/2024.1-RPGym#33]
## Descrição da História

Eu, como usuário, gostaria de retirar um usuário que está no grupo o qual sou administrador.

## tasks

As seguintes tasks devem ser completadas para concluir a história

- [ ] O sistema deve permitir que o usuário administrador do grupo possa expulsar um usuário do seu grupo
- [ ] O sistema deve confirmar pedido de expulsão do usuário
- [ ] O sistema deverá eliminar e bloquear o acesso do usuário o qual o usuário administrador do grupo expulsou

## Critérios de avaliação

- [ ] Visualizar a opção de expulsar jogador
- [ ] Confirmar a expulsão do usuário
- [ ] Tirar o usuário com o pedido de expulsão do grupo.
