### ISSUE TITLE
US19 - Editar o personagem

### ISSUE THREAD

**Issue by DaviRogs** [mdsreq-fga-unb/2024.1-RPGym#34]
## Descrição da História

Eu, como usuário, gostaria de editar meu personagem criado anteriormente.

##  Tasks
As seguintes tasks devem ser completas para concluir a história

- [ ] O sistema deve permitir que o usuário edite seu personagem
- [ ] O sistema deve possibilitar a escolha de cabelos independente do sexo selecionado, na edição
- [ ] O sistema deve possibilitar a escolha da cor de pele do personagem, na edição
- [ ] O sistema deve possibilitar a escolha de facetas no personagem, na edição
- [ ] O sistema deve possibilitar a escolha de vestimentas do personagem, na edição
- - [ ] O sistema deve possibilitar a alteração de cor da vestimenta escolhida, na edição
- [ ] O sistema deve possibilitar a confirmação do personagem realizado pelo usuário , na edição

## Critérios de avaliação
Seção para os critérios que definem acerca da aceitação da tarefa

- [ ] Visualizar a opção de editar personagem
- [ ] Visualizar o personagem do usuário
- [ ] Alterar o cabelo do personagem
- [ ] Alterar a cor de pele do personagem
- [ ] Alterar as facetar do personagem
- [ ] Alterar as vestimentas do personagem
- [ ] Alterar a cor das vestimentas do personagem
- [ ] Confirmar as mudanças feitas do personagem pelo usuário
